### ISSUE TITLE
Change ui style with new sass template

### ISSUE THREAD

**Issue by d0whc3r** [ChinaCompare/web-react#16]
https://transvelo.github.io/electro/
http://8theme.com/demo/html/mango/preview/index.html
http://8theme.com/demo/html/mango/index-everything.html
http://8theme.com/demo/html/mango/index-fullwidthheader.html

**Comment by d0whc3r** [comment]
https://transvelo.github.io/electro/
http://8theme.com/demo/html/mango/preview/index.html
http://8theme.com/demo/html/mango/index-everything.html
http://8theme.com/demo/html/mango/index-fullwidthheader.html

**Comment by Panthro** [comment]
We might have a problem, if we buy a theme we cannot open source it :-1:

**Comment by d0whc3r** [comment]
http://react.semantic-ui.com/introduction
http://semantic-ui.com/introduction/getting-started.html
